OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
AUDIO_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
# OLED_DRIVER_ENABLE = yes #for bongo cat

WPM_ENABLE = yes
